version: '3.1'
services:
  mongo:
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - 8081:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongodb:/etc/mongo
